D:\advanced LSI\SoC-main\rtl\top_soc.v
D:\advanced LSI\SoC-main\rtl\bus\apb_interconnect.v
D:\advanced LSI\SoC-main\rtl\bus\apb_syscon.v
D:\advanced LSI\SoC-main\rtl\bus\axi_interconnect.v
D:\advanced LSI\SoC-main\rtl\bus\axi_master_adapter.v
D:\advanced LSI\SoC-main\rtl\bus\axi_to_apb_bridge.v
D:\advanced LSI\SoC-main\rtl\common\async_fifo.v
D:\advanced LSI\SoC-main\rtl\common\cdc_bridge.v
D:\advanced LSI\SoC-main\rtl\common\clock_gate.v
D:\advanced LSI\SoC-main\rtl\common\skid_buffer.v
D:\advanced LSI\SoC-main\rtl\core\riscv_pipeline.v
D:\advanced LSI\SoC-main\rtl\core\block_unit\branch_prediction_unit.v
D:\advanced LSI\SoC-main\rtl\core\block_unit\control_unit.v
D:\advanced LSI\SoC-main\rtl\core\block_unit\floating_point_unit.v
D:\advanced LSI\SoC-main\rtl\core\block_unit\forwarding_unit.v
D:\advanced LSI\SoC-main\rtl\core\block_unit\multiplier_divider_unit.v
D:\advanced LSI\SoC-main\rtl\core\block_unit\pipeline_control_unit.v
D:\advanced LSI\SoC-main\rtl\core\pipeline_register\pipeline_register.v
D:\advanced LSI\SoC-main\rtl\core\pipeline_stage\pipeline_stage.v
D:\advanced LSI\SoC-main\rtl\core\register_file\register_file.v
D:\advanced LSI\SoC-main\rtl\debug\debug_module.v
D:\advanced LSI\SoC-main\rtl\debug\dtm_axi_master.v
D:\advanced LSI\SoC-main\rtl\debug\jtag_tap.v
D:\advanced LSI\SoC-main\rtl\debug\rv_debug_module_sba.v
D:\advanced LSI\SoC-main\rtl\debug\rv_jtag_dtm.v
D:\advanced LSI\SoC-main\rtl\interrupt\clint.v
D:\advanced LSI\SoC-main\rtl\interrupt\dma.v
D:\advanced LSI\SoC-main\rtl\interrupt\plic.v
D:\advanced LSI\SoC-main\rtl\memory\axi_ram.v
D:\advanced LSI\SoC-main\rtl\memory\axi_rom.v
D:\advanced LSI\SoC-main\rtl\memory\axi_sdram_controller.v
D:\advanced LSI\SoC-main\rtl\memory\axi_spi_flash.v
D:\advanced LSI\SoC-main\rtl\memory\cache\dcache.v
D:\advanced LSI\SoC-main\rtl\memory\cache\icache.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_accel.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_gpio.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_i2c.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_spi.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_timer.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_uart.v
D:\advanced LSI\SoC-main\rtl\peripheral\apb_watchdog.v
D:\advanced LSI\SoC-main\rtl\peripheral\interrupt_controller.v
